export const HANDLE_INPUT_FOCUS = 'header/handle_input_focus'
export const HANDLE_INPUT_BLUR = 'header/handle_input_blur'
export const GET_SEARCH_LIST = 'header/get_search_list'
export const SET_SEARCH_LIST = 'header/set_search_list'
export const MOUSE_ENTER_SEARCH = 'header/mouse_enter_search'
export const MOUSE_LEAVE_SEARCH = 'header/mouse_leave_search'
export const HANDLE_CHANGE_PAGE = 'header/handle_change_page'
